server:
  port: 19012
  tomcat:
    uri-encoding: UTF-8

logging:
  config: /opt/config/customer/conf/log4j2.xml
  level:
    org:
      springframework:
        web: INFO

mybatis:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  type-aliases-package: com.ftvalue.customer.repository

spring:
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    template-loader-path: classpath:/templates/
    suffix: .ftl


  application: customer
  jackson:
     serialization: true
     time-zone: GMT+8
  datasources:
    ismp:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@139.224.36.65:1525:paydb
      username: YaoTdH61ovRHic7XiTKj/qobeXKcdoa4hTwbDC34y3wkKfWDqMbIsOZc7d+kH3oo0DqQCogqOzbvgd6thfz6Ow==
      password: YaoTdH61ovRHic7XiTKj/qobeXKcdoa4hTwbDC34y3wkKfWDqMbIsOZc7d+kH3oo0DqQCogqOzbvgd6thfz6Ow==
      #druid连接池配置
      druid:
        #初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 300
        #配置获取连接等待超时的时间
        maxWait: 60000
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        #配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        #通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
        #合并多个DruidDataSource的监控数据
        #useGlobalDataSourceStat: true
    boss:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@139.224.36.65:1525:paydb
      username: N0G8mmtSWxboocSpsfItkh9F4PkJ9ureLjOiyofwEloKrvs+vMN+CLKprilOsYOvd+/mgXTYm27FUoFJx/CVgg==
      password: N0G8mmtSWxboocSpsfItkh9F4PkJ9ureLjOiyofwEloKrvs+vMN+CLKprilOsYOvd+/mgXTYm27FUoFJx/CVgg==
      #druid连接池配置
      druid:
        #初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 300
        #配置获取连接等待超时的时间
        maxWait: 60000
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        #配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        #通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
        #合并多个DruidDataSource的监控数据
        #useGlobalDataSourceStat: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
  activemq:
    broker-url: failover://tcp://106.15.195.17:61616

  pid:
    file: /opt/logs/customer/application.pids

ismpProps:
  account: http://106.15.195.17:8112/Account
  ismpEimsSms: http://106.15.195.17:18190/sendMessage/sms
  ismpEimsEmail: http://114.215.242.9:18190/inAccess/email
  ismpUrl: http://106.15.195.17:19015
  ismpOldURL: http://106.15.195.17:18180
  userId: rongpay
  userPwd: 123456

rest:
  connection:
    connection-request-timeout: 10000
    connect-timeout: 10000
    read-timeout: 10000


#控制添加角色数量
role_Num: 6

management:
  security:
    enabled: false
